name: Sample

on:
  push:
    branches: 
      - main
  workflow_dispatch:

jobs:
  install-python-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.3.0
      - name: Setup Python
        uses: actions/setup-python@v4
          with:
            python-version: '3.10'
            
      - name: check version
        run: |
          python -v

  defalut-python-version:
    runs-on: ubuntu-latest
      - name: check version
        run: |
          python -v
  